import Head from 'next/head'

const Home = () => {
    return (
        <div>
            <Head>
                <title>22 Create Next App</title>
                <meta name='description' content='Generated by creat next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            Hello Worlrg!!!
        </div>
    )
}

export default Home
